### ISSUE TITLE
一个Goindex的魔改版本 | 赖小瑜

### ISSUE THREAD

**Issue by laixiaoyu-v** [laixiaoyu-v/laixiaoyu-v.github.io#1]
https://blog.likexy.me/posts/a3ab42cc/ 

 关于Goindex GoIndex是一款部署在Cloudflare Workers的Google Drive目录索引程序，无需提供服务器，可以直接列出你谷歌网盘的所有文件，同时下载和访问也不需要挂梯子，也可以在线观看某些格式的视频文件。  原版Github地址：https://github.com/donwa/goindex 原版作者由于某些原因已经删库。 这次主要介绍的是基于原版Goindex的

**Comment by laixiaoyu-v** [comment]
路过一下下。。。。。。

**Comment by luomo28** [comment]
一楼？？
